import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/menu'
import { Box, Container, H1, H3, Text, CTA } from '@/components/globals'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Menu></Menu>
        
        <Container style={{backgroundImage:"url('/Landing.svg')", width:"100%", height:"100vh", backgroundRepeat:"no-repeat", backgroundSize:"cover", justifyContent:"center", alignItems:"flex-end", margin:"-120px 0px 500px -10px"}}>
          <Box flexDir="column" width="40%" minHeight="fit-content" padding="0 30px">
            <H3 color="#B23C87" fSize="25px" padding="10px 0">FRONT-END DEVELOPER</H3>
            <H1 color='#EA638D' fSize="65px" padding="10px 0">Ana Arango</H1>
            <Text color="white" padding="50px 0">A passionate Front-End Developer with a mission to find newer challenges in improving amazing user experiences optimization and visually-appealing websites and web-applications.</Text>
            <CTA>Don't Be A Stranger</CTA>
          </Box>
          <Box width="50%">
            <Image src="/Hero.gif" width={150} height={100} style={{width:"100%", height:"fit-content"}}></Image>
          </Box>
        </Container>

      </main>
    </>
  )
}
